### ISSUE TITLE
Add New Connector - CircleCI

### ISSUE THREAD

**Issue by franloza** [MeltanoLabs/Meta#10]
Developed using Meltano SDK

cc @tayloramurphy @pnadolny13

**Comment by edgarrmondragon** [comment]
Hi @franloza! Do you want to only publish the new tap to Meltano Hub or also move it to the MeltanoLabs namespace?

**Comment by pnadolny13** [comment]
@franloza thanks for creating the issue! In addition to @edgarrmondragon 's questions - did you already develop this tap and want to migrate it or are you hoping to develop it within the MeltanoLabs namespace?

**Comment by franloza** [comment]
> Do you want to only publish the new tap to Meltano Hub or also move it to the MeltanoLabs namespace?

@edgarrmondragon Both! I would be happy to be the maintainer of this repository in this ecosystem.

>  did you already develop this tap and want to migrate it or are you hoping to develop it within the MeltanoLabs namespace?

@pnadolny13 I have a "0.1" version working on my computer with a couple of streams implemented, but the tap is still in development. So I'd like to continue developing it within the MeltanoLabs namespace.

**Comment by pnadolny13** [comment]
@franloza Awesome! I created [a repo](https://github.com/MeltanoLabs/tap-circle-ci) and added you to the team that has access to maintain it. Let me know if you have any issues accessing it. When are you expecting initial development to be done? Once its Beta we can add it to MeltanoHub and eventually set it as the default variant when its more tested and hardened.

**Comment by franloza** [comment]
Hey @pnadolny13. I didn't have any issues uploading the code. I expect to finish the initial development in the next few days. The tap works locally but I'd like to test it with some targets and multiple repos. I'll add a `CHANGELOG.md` file and a `0.1` tag when it's ready. Thank you 👏

**Comment by franloza** [comment]
The first version is ready 🎉 https://github.com/MeltanoLabs/tap-circle-ci/releases/tag/0.1.0

**Comment by aaronsteers** [comment]
@franloza - Exciting! Thanks for sharing this back with us - and the community!
