### ISSUE TITLE
Migrate Existing Connector - tap-mongodb

### ISSUE THREAD

**Issue by menzenski** [MeltanoLabs/Meta#44]
@tayloramurphy @pnadolny13 

Per https://github.com/MeltanoLabs/Meta#migrating-an-existing-connector I'd like to migrate my tap-mongodb plugin to MeltanoLabs. I'm interested to continue as maintainer indefinitely, but am interested to see this tap move within the MeltanoLabs community organization.

Repository: https://github.com/menzenski/tap-mongodb
Hub page: https://hub.meltano.com/extractors/tap-mongodb--menzenski/

**Comment by kgpayne** [comment]
Amazing, thanks @menzenski 🙌 I can help with this.

As your Tap is on the Hub, we want to be careful about breaking existing users. Broadly the steps are:

- Create a PR to the Hub repo with two changes:
	- Adding a new `.yml` for a MeltanoLabs variant of `tap-mongodb`, pointing at `MeltanoLabs/tap-mongodb` in GitHub.
	- Updating your existing `.yml` to also point at `MeltanoLabs/tap-mongodb` _and_ setting `hidden: true` in the config.
- Initiate and accept transfer of Repo in GitHub from `menzenski/` to `MeltanoLabs/` and merge Hub PR.

Leaving your existing variant in place (but hidden and redirected to `MeltanoLabs/`) ensures that any projects using it won't break. Any future projects can use the visible MeltanoLabs variant going forward.

@pnadolny13 did I miss anything?

**Comment by menzenski** [comment]
Thanks @kgpayne - I'll get this together early next week!

**Comment by menzenski** [comment]
@kgpayne apologies for the delay in getting this transferred.

I've opened the PR for the Hub: https://github.com/meltano/hub/pull/1437

But I'm not able to transfer the repository to the MeltanoLabs organization:

<img width="731" alt="Screen Shot 2023-07-17 at 11 01 22 PM" src="https://github.com/MeltanoLabs/Meta/assets/4371752/918c2c52-3c4e-4b37-817d-3bfcd716a9fc">

**Comment by pnadolny13** [comment]
cc @edgarrmondragon @WillDaSilva @tayloramurphy how do we normally do this transfer? Do we give Matt access or does he need to give us access?

**Comment by WillDaSilva** [comment]
@pnadolny13 I've invited @menzenski to join MeltanoLabs as a member, which provides the permission to create new repositories.

@menzenski After you accept the invitation, could you please re-attempt the transfer

**Comment by WillDaSilva** [comment]
New MeltanoLabs team for tap-mongodb: https://github.com/orgs/MeltanoLabs/teams/tap-mongodb

**Comment by pnadolny13** [comment]
Closing this since the repo was migrated https://github.com/MeltanoLabs/tap-mongodb and is listed on the hub https://hub.meltano.com/extractors/tap-mongodb--meltanolabs/. 🚀
