### ISSUE TITLE
Add New Connector - tap-google-search-console

### ISSUE THREAD

**Issue by acarter24** [MeltanoLabs/Meta#55]
Hi, I have built a private tap for Google Search Console which I have been given permission to contribute to MeltanoLabs.

https://developers.google.com/webmaster-tools/v1/api_reference_index

At present the tap just exists on our private Azure DevOps server, but I would like to add to Meltanolabs and happy to act as maintainer.

I'm running through some of the guides on the Meta repo to get my private version up to snuff, what are next steps to allow me to push the repo to meltanolabs?

**Comment by edgarrmondragon** [comment]
I'm not familiar with Azure DEvOps, but they might have documentation on how to transfer a repository to GitHub.

**Comment by pnadolny13** [comment]
> I'm not familiar with Azure DevOps, but they might have documentation on how to transfer a repository to GitHub.

@acarter24 I think Azure DevOps is a standard git repository so I think an approach would be to mirror it and push that up to github. https://www.atlassian.com/git/tutorials/git-move-repository seems like a reasonable approach.

**Comment by edgarrmondragon** [comment]
> I have pushed an initial version for any comment or testing you can offer. I have been using this code in production for nearly 12 months, so happy it is stable for my setup, but good to get someone else to try it out.

Thanks @acarter24! We'll get it added to the Hub.

**Comment by edgarrmondragon** [comment]
https://github.com/meltano/hub/issues/1901

**Comment by edgarrmondragon** [comment]
https://hub.meltano.com/extractors/tap-google-search-console/

Thanks @acarter24!
